//
// Generated by JTB 1.3.2
//

package jplasma.syntaxtree;

/**
 * Grammar production:
 * nodeChoice -> ExpressionInParentheses()
 *       | ConditionalOrExpression()
 *       | SimpleDistributionExpression()
 *       | ConditionalAndExpression()
 *       | InclusiveOrExpression()
 *       | ExclusiveOrExpression()
 *       | AndExpression()
 *       | EqualsExpression()
 *       | NonEqualsExpression()
 *       | LessThanExpression()
 *       | GreaterThanExpression()
 *       | LessThanEqualExpression()
 *       | GreaterThanEqualExpression()
 *       | ShiftLeftExpression()
 *       | ShiftRightExpression()
 *       | ShiftRightUnsignedExpression()
 *       | PlusOffset()
 *       | PlusExpression()
 *       | MinusExpression()
 *       | TimesOffset()
 *       | TimesExpression()
 *       | DivideOffset()
 *       | DivideExpression()
 *       | ModulusExpression()
 *       | RegionConstant()
 *       | SinExpression()
 *       | CosExpression()
 *       | PowExpression()
 *       | ExpExpression()
 *       | SqrtExpression()
 *       | AbsExpression()
 *       | MinExpression()
 *       | MaxExpression()
 *       | LogExpression()
 *       | ComplimentExpression()
 *       | NotExpression()
 *       | CoercionToIntExpression()
 *       | CoercionToDoubleExpression()
 *       | CoercionToLongExpression()
 *       | CoercionToShortExpression()
 *       | CoercionToByteExpression()
 *       | TypeAnnotatedExpression()
 *       | Place()
 *       | CurrentTime()
 *       | ArrayAccess()
 *       | PointAccess()
 *       | MethodCall()
 *       | MethodCallInConstructor()
 *       | DotId()
 *       | DotIdentifierDotGet()
 *       | DotNext()
 *       | DotPrev()
 *       | DotIsFirst()
 *       | DotIsLast()
 *       | DotRegionDotSize()
 *       | DotIdentifier()
 *       | NewObject()
 *       | NewValueArray()
 *       | NewUpdatableArray()
 *       | IntegerLiteral()
 *       | LongLiteral()
 *       | HexLiteral()
 *       | FloatingPointLiteral()
 *       | StringLiteral()
 *       | True()
 *       | False()
 *       | HereLiteral()
 *       | PlaceFirstPlace()
 *       | PlaceLastPlace()
 *       | PlaceMaxPlaces()
 *       | JavaIntegerSize()
 *       | Identifier()
 */
public class Expression implements Node {
   public NodeChoice nodeChoice;

   public Expression(NodeChoice n0) {
      nodeChoice = n0;
   }

   public void accept(jplasma.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasma.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasma.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasma.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

