//
// Generated by JTB 1.3.2
//

package jplasma.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> ","
 * finalFormalParameter -> FinalFormalParameter()
 */
public class FormalParameterRest implements Node {
   public NodeToken nodeToken;
   public FinalFormalParameter finalFormalParameter;

   public FormalParameterRest(NodeToken n0, FinalFormalParameter n1) {
      nodeToken = n0;
      finalFormalParameter = n1;
   }

   public FormalParameterRest(FinalFormalParameter n0) {
      nodeToken = new NodeToken(",");
      finalFormalParameter = n0;
   }

   public void accept(jplasma.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasma.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasma.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasma.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

