//
// Generated by JTB 1.3.2
//

package jplasma.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "this"
 * nodeToken1 -> "."
 * identifier -> Identifier()
 * nodeToken2 -> "("
 * nodeOptional -> ( IdentifierList() )?
 * nodeToken3 -> ")"
 */
public class MethodCallInConstructor implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public Identifier identifier;
   public NodeToken nodeToken2;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken3;

   public MethodCallInConstructor(NodeToken n0, NodeToken n1, Identifier n2, NodeToken n3, NodeOptional n4, NodeToken n5) {
      nodeToken = n0;
      nodeToken1 = n1;
      identifier = n2;
      nodeToken2 = n3;
      nodeOptional = n4;
      nodeToken3 = n5;
   }

   public MethodCallInConstructor(Identifier n0, NodeOptional n1) {
      nodeToken = new NodeToken("this");
      nodeToken1 = new NodeToken(".");
      identifier = n0;
      nodeToken2 = new NodeToken("(");
      nodeOptional = n1;
      nodeToken3 = new NodeToken(")");
   }

   public void accept(jplasma.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasma.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasma.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasma.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

