package plasmax10.parser;
/* Generated By:JavaCC: Do not edit this line. PlasmaX10ParserConstants.java */
public interface PlasmaX10ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int LSQPAREN = 11;
  int RSQPAREN = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int SEMICOLON = 15;
  int DOT = 16;
  int ASSIGN = 17;
  int LT = 18;
  int PLUS = 19;
  int MINUS = 20;
  int AND = 21;
  int NOT = 22;
  int QUESTION = 23;
  int CLASS = 24;
  int VALUE = 25;
  int FINAL = 26;
  int IF = 27;
  int ELSE = 28;
  int FALSE = 29;
  int TRUE = 30;
  int WHILE = 31;
  int VOID = 32;
  int BOOLEAN = 33;
  int INTEGER = 34;
  int NEW = 35;
  int GET = 36;
  int CONTAINS = 37;
  int HIGH = 38;
  int LOW = 39;
  int NEXT = 40;
  int PREV = 41;
  int ISFIRST = 42;
  int ISLAST = 43;
  int COORD = 44;
  int ORDINAL = 45;
  int PUBLIC = 46;
  int RETURN = 47;
  int STATIC = 48;
  int STRING = 49;
  int THIS = 50;
  int PRINTLN = 51;
  int PRINT = 52;
  int PRINTERROR = 53;
  int CURRENTTIME = 54;
  int ADDLOCALOPS = 55;
  int JAVAIOSIZE = 56;
  int FACTORYPlace = 57;
  int FACTORYBlock = 58;
  int FACTORYEMPTYREGION = 59;
  int FACTORYPOINT = 60;
  int JAVALANGOBJECT = 61;
  int BREAK = 62;
  int SUPER = 63;
  int THROW = 64;
  int RUNTIMEEXCEPTION = 65;
  int DOUBLE = 66;
  int LONG = 67;
  int SHORT = 68;
  int BYTE = 69;
  int REGION = 70;
  int ID = 71;
  int PLACES = 72;
  int RANK = 73;
  int DISTRIBUTION = 74;
  int DIST = 75;
  int SWITCH = 76;
  int ATEACH = 77;
  int FINISH = 78;
  int MAIN = 79;
  int MATH = 80;
  int SIN = 81;
  int COS = 82;
  int POW = 83;
  int EXP = 84;
  int SQRT = 85;
  int ABS = 86;
  int PLACE = 87;
  int MIN = 88;
  int MAX = 89;
  int LOG = 90;
  int SUM = 91;
  int SIZE = 92;
  int EQUALS = 93;
  int PRIVATE = 94;
  int FOREACH = 95;
  int FINALLY = 96;
  int POINT = 97;
  int CONTINUE = 98;
  int INSTANCEOF = 99;
  int DO = 100;
  int FOR = 101;
  int HERE = 102;
  int DISTUNIQUE = 103;
  int CASE = 104;
  int ASYNC = 105;
  int OR = 106;
  int DEFAULT_TOKEN = 107;
  int INTEGER_LITERAL = 108;
  int POINT_LITERAL = 109;
  int DECIMAL_LITERAL = 110;
  int HEX_LITERAL = 111;
  int LONG_LITERAL = 112;
  int OCTAL_LITERAL = 113;
  int FLOATING_POINT_LITERAL = 114;
  int EXPONENT = 115;
  int CHARACTER_LITERAL = 116;
  int STRING_LITERAL = 117;
  int IDENTIFIER = 118;
  int LETTER = 119;
  int DIGIT = 120;
  int RUNSIGNEDSHIFT = 121;
  int RSIGNEDSHIFT = 122;
  int GT = 123;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"&&\"",
    "\"!\"",
    "\"?\"",
    "\"class\"",
    "\"value\"",
    "\"final\"",
    "\"if\"",
    "\"else\"",
    "\"false\"",
    "\"true\"",
    "\"while\"",
    "\"void\"",
    "\"boolean\"",
    "\"int\"",
    "\"new\"",
    "\"get\"",
    "\"contains\"",
    "\"high\"",
    "\"low\"",
    "\"next\"",
    "\"prev\"",
    "\"isFirst\"",
    "\"isLast\"",
    "\"coord\"",
    "\"ordinal\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\"System.out.println\"",
    "\"System.out.print\"",
    "\"System.err.println\"",
    "\"System.currentTimeMillis\"",
    "\"x10.lang.perf.addLocalOps\"",
    "\"java.io.Integer.SIZE\"",
    "\"dist.factory.place\"",
    "\"dist.factory.block\"",
    "\"region.factory.emptyRegion\"",
    "\"point.factory.point\"",
    "\"java.lang.Object\"",
    "\"break\"",
    "\"super\"",
    "\"throw\"",
    "\"RuntimeException\"",
    "\"double\"",
    "\"long\"",
    "\"short\"",
    "\"byte\"",
    "\"region\"",
    "\"id\"",
    "\"place.places\"",
    "\"rank\"",
    "\"distribution\"",
    "\"dist\"",
    "\"switch\"",
    "\"ateach\"",
    "\"finish\"",
    "\"main\"",
    "\"Math\"",
    "\"sin\"",
    "\"cos\"",
    "\"pow\"",
    "\"exp\"",
    "\"sqrt\"",
    "\"abs\"",
    "\"place\"",
    "\"min\"",
    "\"max\"",
    "\"log\"",
    "\"sum\"",
    "\"size\"",
    "\"equals\"",
    "\"private\"",
    "\"foreach\"",
    "\"finally\"",
    "\"point\"",
    "\"continue\"",
    "\"instanceof\"",
    "\"do\"",
    "\"for\"",
    "\"here\"",
    "\"dist.UNIQUE\"",
    "\"case\"",
    "\"async\"",
    "\"or\"",
    "\"default\"",
    "<INTEGER_LITERAL>",
    "<POINT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<LONG_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\",\"",
    "\":\"",
    "\"==\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"->\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"dist.factory.blockCyclic\"",
    "\"place.FIRST_PLACE\"",
    "\"place.LAST_PLACE\"",
    "\"place.MAX_PLACES\"",
    "\"java.lang.Integer.SIZE\"",
  };

}
