//
// Generated by JTB 1.3.2
//

package splasmax10.syntaxtree;

/**
 * Grammar production:
 * f0 -> Identifier()
 * f1 -> "["
 * f2 -> IdentifierList()
 * f3 -> "]"
 * f4 -> "="
 * f5 -> "("
 * f6 -> Identifier()
 * f7 -> ")"
 * f8 -> ";"
 */
public class ArrayAssignment implements Node {
   public Identifier f0;
   public NodeToken f1;
   public IdentifierList f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeToken f5;
   public Identifier f6;
   public NodeToken f7;
   public NodeToken f8;

   public ArrayAssignment(Identifier n0, NodeToken n1, IdentifierList n2, NodeToken n3, NodeToken n4, NodeToken n5, Identifier n6, NodeToken n7, NodeToken n8) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
   }

   public ArrayAssignment(Identifier n0, IdentifierList n1, Identifier n2) {
      f0 = n0;
      f1 = new NodeToken("[");
      f2 = n1;
      f3 = new NodeToken("]");
      f4 = new NodeToken("=");
      f5 = new NodeToken("(");
      f6 = n2;
      f7 = new NodeToken(")");
      f8 = new NodeToken(";");
   }

   public void accept(splasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(splasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(splasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(splasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

