//
// Generated by JTB 1.3.2
//

package splasmax10.syntaxtree;

/**
 * Grammar production:
 * f0 -> "case"
 * f1 -> Identifier()
 */
public class Case implements Node {
   public NodeToken f0;
   public Identifier f1;

   public Case(NodeToken n0, Identifier n1) {
      f0 = n0;
      f1 = n1;
   }

   public Case(Identifier n0) {
      f0 = new NodeToken("case");
      f1 = n0;
   }

   public void accept(splasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(splasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(splasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(splasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

