//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * identifier -> Identifier()
 * nodeToken -> "/"
 * nodeToken1 -> "["
 * identifierList -> IdentifierList()
 * nodeToken2 -> "]"
 */
public class DivideOffset implements Node {
   public Identifier identifier;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public IdentifierList identifierList;
   public NodeToken nodeToken2;

   public DivideOffset(Identifier n0, NodeToken n1, NodeToken n2, IdentifierList n3, NodeToken n4) {
      identifier = n0;
      nodeToken = n1;
      nodeToken1 = n2;
      identifierList = n3;
      nodeToken2 = n4;
   }

   public DivideOffset(Identifier n0, IdentifierList n1) {
      identifier = n0;
      nodeToken = new NodeToken("/");
      nodeToken1 = new NodeToken("[");
      identifierList = n1;
      nodeToken2 = new NodeToken("]");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

