//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "place.FIRST_PLACE"
 */
public class PlaceFirstPlace implements Node {
   public NodeToken nodeToken;

   public PlaceFirstPlace(NodeToken n0) {
      nodeToken = n0;
   }

   public PlaceFirstPlace() {
      nodeToken = new NodeToken("place.FIRST_PLACE");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

