//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "value"
 * identifier -> Identifier()
 * nodeToken1 -> "{"
 * nodeListOptional -> ( InitializableConstantDeclaration() )*
 * nodeListOptional1 -> ( ConstructorDeclaration() )*
 * nodeListOptional2 -> ( MethodDeclaration() )*
 * nodeToken2 -> "}"
 */
public class ValueDeclaration implements Node {
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeToken nodeToken1;
   public NodeListOptional nodeListOptional;
   public NodeListOptional nodeListOptional1;
   public NodeListOptional nodeListOptional2;
   public NodeToken nodeToken2;

   public ValueDeclaration(NodeToken n0, Identifier n1, NodeToken n2, NodeListOptional n3, NodeListOptional n4, NodeListOptional n5, NodeToken n6) {
      nodeToken = n0;
      identifier = n1;
      nodeToken1 = n2;
      nodeListOptional = n3;
      nodeListOptional1 = n4;
      nodeListOptional2 = n5;
      nodeToken2 = n6;
   }

   public ValueDeclaration(Identifier n0, NodeListOptional n1, NodeListOptional n2, NodeListOptional n3) {
      nodeToken = new NodeToken("value");
      identifier = n0;
      nodeToken1 = new NodeToken("{");
      nodeListOptional = n1;
      nodeListOptional1 = n2;
      nodeListOptional2 = n3;
      nodeToken2 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

