//
// Generated by JTB 1.3.2
//

package plasmax10.syntaxtree;

/**
 * Grammar production:
 * f0 -> Visibility()
 * f1 -> Type()
 * f2 -> Identifier()
 * f3 -> ";"
 */
public class UpdatableFieldDeclaration implements Node {
   public Visibility f0;
   public Type f1;
   public Identifier f2;
   public NodeToken f3;

   public UpdatableFieldDeclaration(Visibility n0, Type n1, Identifier n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public UpdatableFieldDeclaration(Visibility n0, Type n1, Identifier n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = new NodeToken(";");
   }

   public void accept(plasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(plasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(plasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(plasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

