//
// Generated by JTB 1.3.2
//

package jplasma.syntaxtree;

/**
 * Grammar production:
 * methodCall -> MethodCall()
 * nodeToken -> ";"
 */
public class MethodCallStatement implements Node {
   public MethodCall methodCall;
   public NodeToken nodeToken;

   public MethodCallStatement(MethodCall n0, NodeToken n1) {
      methodCall = n0;
      nodeToken = n1;
   }

   public MethodCallStatement(MethodCall n0) {
      methodCall = n0;
      nodeToken = new NodeToken(";");
   }

   public void accept(jplasma.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasma.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasma.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasma.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

