//
// Generated by JTB 1.3.2
//

package uplasmax10.visitor;
import uplasmax10.syntaxtree.*;

import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated uplasmax10.visitor methods below
   //

   /**
    * mainClass -> MainClass()
    * programClass -> ProgramClass()
    * nodeListOptional -> ( TopLevelDeclaration() )*
    * nodeToken -> <EOF>
    */
   public void visit(File n) {
      n.mainClass.accept(this);
      n.programClass.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "class"
    * identifier -> Identifier()
    * nodeToken2 -> "{"
    * nodeToken3 -> "public"
    * nodeToken4 -> "static"
    * nodeToken5 -> "void"
    * nodeToken6 -> "main"
    * nodeToken7 -> "("
    * nodeToken8 -> "String"
    * nodeToken9 -> "["
    * nodeToken10 -> "]"
    * identifier1 -> Identifier()
    * nodeToken11 -> ")"
    * nodeToken12 -> "{"
    * identifier2 -> Identifier()
    * nodeToken13 -> "."
    * identifier3 -> Identifier()
    * nodeToken14 -> "("
    * nodeToken15 -> ")"
    * nodeToken16 -> ";"
    * nodeToken17 -> "}"
    * nodeToken18 -> "}"
    */
   public void visit(MainClass n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
      n.nodeToken8.accept(this);
      n.nodeToken9.accept(this);
      n.nodeToken10.accept(this);
      n.identifier1.accept(this);
      n.nodeToken11.accept(this);
      n.nodeToken12.accept(this);
      n.identifier2.accept(this);
      n.nodeToken13.accept(this);
      n.identifier3.accept(this);
      n.nodeToken14.accept(this);
      n.nodeToken15.accept(this);
      n.nodeToken16.accept(this);
      n.nodeToken17.accept(this);
      n.nodeToken18.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( ConstantDeclaration() )*
    * nodeListOptional1 -> ( StaticMethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ProgramClass n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeChoice -> ClassDeclaration()
    *       | ValueDeclaration()
    */
   public void visit(TopLevelDeclaration n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( InitializableConstantDeclaration() )*
    * nodeListOptional1 -> ( UpdatableFieldDeclaration() )*
    * nodeListOptional2 -> ( ConstructorDeclaration() )*
    * nodeListOptional3 -> ( MethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ClassDeclaration n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeListOptional2.accept(this);
      n.nodeListOptional3.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "value"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( InitializableConstantDeclaration() )*
    * nodeListOptional1 -> ( ConstructorDeclaration() )*
    * nodeListOptional2 -> ( MethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ValueDeclaration n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeListOptional1.accept(this);
      n.nodeListOptional2.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "public"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(ConstructorDeclaration n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken2.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "static"
    * nodeToken2 -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken3 -> "="
    * methodCall -> MethodCall()
    * nodeToken4 -> ";"
    */
   public void visit(ConstantDeclaration n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken3.accept(this);
      n.methodCall.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken2 -> ";"
    */
   public void visit(InitializableConstantDeclaration n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "public"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> ";"
    */
   public void visit(UpdatableFieldDeclaration n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "static"
    * returnType -> ReturnType()
    * identifier -> Identifier()
    * nodeToken2 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken3 -> ")"
    * block -> Block()
    */
   public void visit(StaticMethodDeclaration n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.returnType.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken3.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeToken -> "public"
    * returnType -> ReturnType()
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(MethodDeclaration n) {
      n.nodeToken.accept(this);
      n.returnType.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken2.accept(this);
      n.block.accept(this);
   }

   /**
    * finalFormalParameter -> FinalFormalParameter()
    * nodeListOptional -> ( FormalParameterRest() )*
    */
   public void visit(FormalParameterList n) {
      n.finalFormalParameter.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * nodeToken -> "final"
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(FinalFormalParameter n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> ","
    * finalFormalParameter -> FinalFormalParameter()
    */
   public void visit(FormalParameterRest n) {
      n.nodeToken.accept(this);
      n.finalFormalParameter.accept(this);
   }

   /**
    * nodeChoice -> VoidType()
    *       | Type()
    */
   public void visit(ReturnType n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "void"
    */
   public void visit(VoidType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> UpdatableArrayType()
    *       | ValueArrayType()
    *       | NonArrayType()
    */
   public void visit(Type n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nonArrayType -> NonArrayType()
    * nodeToken -> "["
    * nodeToken1 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken2 -> "]"
    */
   public void visit(UpdatableArrayType n) {
      n.nonArrayType.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nonArrayType -> NonArrayType()
    * nodeToken -> "value"
    * nodeToken1 -> "["
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> "]"
    */
   public void visit(ValueArrayType n) {
      n.nonArrayType.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "rank==1"
    */
   public void visit(RankEquation n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> BooleanType()
    *       | ByteType()
    *       | ShortType()
    *       | IntegerType()
    *       | LongType()
    *       | DoubleType()
    *       | StringType()
    *       | PlaceType()
    *       | DistType()
    *       | RegionType()
    *       | PointType()
    *       | ClassNameType()
    */
   public void visit(NonArrayType n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "boolean"
    */
   public void visit(BooleanType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "byte"
    */
   public void visit(ByteType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "short"
    */
   public void visit(ShortType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "int"
    */
   public void visit(IntegerType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "long"
    */
   public void visit(LongType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "double"
    */
   public void visit(DoubleType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "String"
    */
   public void visit(StringType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "place"
    */
   public void visit(PlaceType n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "dist"
    * nodeToken1 -> "("
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> ")"
    */
   public void visit(DistType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "region"
    * nodeToken1 -> "("
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> ")"
    */
   public void visit(RegionType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "point"
    * nodeToken1 -> "("
    * nodeToken2 -> ":"
    * rankEquation -> RankEquation()
    * nodeToken3 -> ")"
    */
   public void visit(PointType n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.rankEquation.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    */
   public void visit(ClassNameType n) {
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "{"
    * nodeListOptional -> ( Statement() )*
    * nodeToken1 -> "}"
    */
   public void visit(Block n) {
      n.nodeToken.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeChoice -> Assignment()
    *       | ArrayAssignment()
    *       | FieldAssignment()
    *       | ThisFieldAssignment()
    *       | AsyncStatement()
    *       | AsyncStatementInConstructor()
    *       | Block()
    *       | BreakStatement()
    *       | ContinueStatement()
    *       | DoStatement()
    *       | FinishStatement()
    *       | IfStatement()
    *       | LoopStatement()
    *       | MethodCallStatement()
    *       | MethodCallStatementInConstructor()
    *       | PrintlnStatement()
    *       | PrintStatement()
    *       | PrintErrorStatement()
    *       | ReturnStatement()
    *       | SwitchStatement()
    *       | ThrowStatement()
    *       | WhileStatement()
    *       | FinalVariableDeclaration()
    *       | UpdatableVariableDeclaration()
    */
   public void visit(Statement n) {
      n.nodeChoice.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(Assignment n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * identifierList -> IdentifierList()
    * nodeToken1 -> "]"
    * nodeToken2 -> "="
    * nodeToken3 -> "("
    * identifier1 -> Identifier()
    * nodeToken4 -> ")"
    * nodeToken5 -> ";"
    */
   public void visit(ArrayAssignment n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifierList.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier1.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    * nodeToken1 -> "="
    * nodeToken2 -> "("
    * identifier2 -> Identifier()
    * nodeToken3 -> ")"
    * nodeToken4 -> ";"
    */
   public void visit(FieldAssignment n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.identifier2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "this"
    * nodeToken1 -> "."
    * identifier -> Identifier()
    * nodeToken2 -> "="
    * nodeToken3 -> "("
    * identifier1 -> Identifier()
    * nodeToken4 -> ")"
    * nodeToken5 -> ";"
    */
   public void visit(ThisFieldAssignment n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier1.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "async"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * identifier1 -> Identifier()
    * nodeToken4 -> "."
    * identifier2 -> Identifier()
    * nodeToken5 -> "("
    * identifier3 -> Identifier()
    * nodeToken6 -> ")"
    * nodeToken7 -> ";"
    * nodeToken8 -> "}"
    */
   public void visit(AsyncStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier1.accept(this);
      n.nodeToken4.accept(this);
      n.identifier2.accept(this);
      n.nodeToken5.accept(this);
      n.identifier3.accept(this);
      n.nodeToken6.accept(this);
      n.nodeToken7.accept(this);
      n.nodeToken8.accept(this);
   }

   /**
    * nodeToken -> "async"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * nodeToken4 -> "this"
    * nodeToken5 -> "."
    * identifier1 -> Identifier()
    * nodeToken6 -> "("
    * identifier2 -> Identifier()
    * nodeToken7 -> ")"
    * nodeToken8 -> ";"
    * nodeToken9 -> "}"
    */
   public void visit(AsyncStatementInConstructor n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
      n.identifier1.accept(this);
      n.nodeToken6.accept(this);
      n.identifier2.accept(this);
      n.nodeToken7.accept(this);
      n.nodeToken8.accept(this);
      n.nodeToken9.accept(this);
   }

   /**
    * nodeToken -> "break"
    * nodeToken1 -> ";"
    */
   public void visit(BreakStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "continue"
    * nodeToken1 -> ";"
    */
   public void visit(ContinueStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "do"
    * block -> Block()
    * nodeToken1 -> "while"
    * nodeToken2 -> "("
    * identifier -> Identifier()
    * nodeToken3 -> ")"
    * nodeToken4 -> ";"
    */
   public void visit(DoStatement n) {
      n.nodeToken.accept(this);
      n.block.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.identifier.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "finish"
    * block -> Block()
    */
   public void visit(FinishStatement n) {
      n.nodeToken.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeToken -> "if"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * block -> Block()
    * nodeOptional -> [ ElseClause() ]
    */
   public void visit(IfStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.block.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * nodeToken -> "else"
    * block -> Block()
    */
   public void visit(ElseClause n) {
      n.nodeToken.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeToken -> "for"
    * nodeToken1 -> "("
    * pointType -> PointType()
    * explodedSpecification -> ExplodedSpecification()
    * nodeToken2 -> ":"
    * identifier -> Identifier()
    * nodeToken3 -> ")"
    * block -> Block()
    */
   public void visit(LoopStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.pointType.accept(this);
      n.explodedSpecification.accept(this);
      n.nodeToken2.accept(this);
      n.identifier.accept(this);
      n.nodeToken3.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeChoice -> PointName()
    *       | Coordinates()
    */
   public void visit(ExplodedSpecification n) {
      n.nodeChoice.accept(this);
   }

   /**
    * identifier -> Identifier()
    */
   public void visit(PointName n) {
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> "["
    * identifier -> Identifier()
    * nodeToken1 -> "]"
    */
   public void visit(Coordinates n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeListOptional -> ( IdentifierRest() )*
    */
   public void visit(IdentifierList n) {
      n.identifier.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * nodeToken -> ","
    * identifier -> Identifier()
    */
   public void visit(IdentifierRest n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
   }

   /**
    * methodCall -> MethodCall()
    * nodeToken -> ";"
    */
   public void visit(MethodCallStatement n) {
      n.methodCall.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * methodCallInConstructor -> MethodCallInConstructor()
    * nodeToken -> ";"
    */
   public void visit(MethodCallStatementInConstructor n) {
      n.methodCallInConstructor.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "System.out.println"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintlnStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "System.out.print"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "System.err.println"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintErrorStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeToken -> "return"
    * nodeOptional -> [ Identifier() ]
    * nodeToken1 -> ";"
    */
   public void visit(ReturnStatement n) {
      n.nodeToken.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeToken -> "switch"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * nodeListOptional -> ( SwitchEntry() )*
    * nodeToken4 -> "}"
    */
   public void visit(SwitchStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * switchLabel -> SwitchLabel()
    * nodeToken -> ":"
    * block -> Block()
    */
   public void visit(SwitchEntry n) {
      n.switchLabel.accept(this);
      n.nodeToken.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeChoice -> Case()
    *       | Default()
    */
   public void visit(SwitchLabel n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "case"
    * identifier -> Identifier()
    */
   public void visit(Case n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> "default"
    */
   public void visit(Default n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "throw"
    * nodeToken1 -> "new"
    * nodeToken2 -> "RuntimeException"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    * nodeToken5 -> ";"
    */
   public void visit(ThrowStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "while"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(WhileStatement n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.block.accept(this);
   }

   /**
    * nodeToken -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> "="
    * expression -> Expression()
    * nodeToken2 -> ";"
    */
   public void visit(FinalVariableDeclaration n) {
      n.nodeToken.accept(this);
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.expression.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(UpdatableVariableDeclaration n) {
      n.type.accept(this);
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * nodeChoice -> ExpressionInParentheses()
    *       | ConditionalOrExpression()
    *       | SimpleDistributionExpression()
    *       | ConditionalAndExpression()
    *       | InclusiveOrExpression()
    *       | ExclusiveOrExpression()
    *       | AndExpression()
    *       | EqualsExpression()
    *       | NonEqualsExpression()
    *       | LessThanExpression()
    *       | GreaterThanExpression()
    *       | LessThanEqualExpression()
    *       | GreaterThanEqualExpression()
    *       | ShiftLeftExpression()
    *       | ShiftRightExpression()
    *       | ShiftRightUnsignedExpression()
    *       | PlusOffset()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesOffset()
    *       | TimesExpression()
    *       | DivideOffset()
    *       | DivideExpression()
    *       | ModulusExpression()
    *       | RegionConstant()
    *       | SinExpression()
    *       | CosExpression()
    *       | PowExpression()
    *       | ExpExpression()
    *       | SqrtExpression()
    *       | AbsExpression()
    *       | MinExpression()
    *       | MaxExpression()
    *       | LogExpression()
    *       | ComplimentExpression()
    *       | NotExpression()
    *       | CoercionToIntExpression()
    *       | CoercionToDoubleExpression()
    *       | CoercionToLongExpression()
    *       | CoercionToShortExpression()
    *       | CoercionToByteExpression()
    *       | TypeAnnotatedExpression()
    *       | Place()
    *       | CurrentTime()
    *       | ArrayAccess()
    *       | PointAccess()
    *       | MethodCall()
    *       | MethodCallInConstructor()
    *       | DotId()
    *       | DotIdentifierDotGet()
    *       | DotNext()
    *       | DotPrev()
    *       | DotIsFirst()
    *       | DotIsLast()
    *       | DotRegionDotSize()
    *       | DotIdentifier()
    *       | NewObject()
    *       | NewValueArray()
    *       | NewUpdatableArray()
    *       | IntegerLiteral()
    *       | LongLiteral()
    *       | HexLiteral()
    *       | FloatingPointLiteral()
    *       | StringLiteral()
    *       | True()
    *       | False()
    *       | HereLiteral()
    *       | PlaceFirstPlace()
    *       | PlaceLastPlace()
    *       | PlaceMaxPlaces()
    *       | JavaIntegerSize()
    *       | Identifier()
    */
   public void visit(Expression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "("
    * expression -> Expression()
    * nodeToken1 -> ")"
    */
   public void visit(ExpressionInParentheses n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "||"
    * identifier1 -> Identifier()
    */
   public void visit(ConditionalOrExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * nodeToken -> "["
    * nodeToken1 -> "0 :"
    * identifier -> Identifier()
    * nodeToken2 -> "]"
    * nodeToken3 -> "->"
    * nodeToken4 -> "here"
    */
   public void visit(SimpleDistributionExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "&&"
    * identifier1 -> Identifier()
    */
   public void visit(ConditionalAndExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "|"
    * identifier1 -> Identifier()
    */
   public void visit(InclusiveOrExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "^"
    * identifier1 -> Identifier()
    */
   public void visit(ExclusiveOrExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "&"
    * identifier1 -> Identifier()
    */
   public void visit(AndExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "=="
    * identifier1 -> Identifier()
    */
   public void visit(EqualsExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "!="
    * identifier1 -> Identifier()
    */
   public void visit(NonEqualsExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "<"
    * identifier1 -> Identifier()
    */
   public void visit(LessThanExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> ">"
    * identifier1 -> Identifier()
    */
   public void visit(GreaterThanExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "<="
    * identifier1 -> Identifier()
    */
   public void visit(LessThanEqualExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> ">="
    * identifier1 -> Identifier()
    */
   public void visit(GreaterThanEqualExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "<<"
    * identifier1 -> Identifier()
    */
   public void visit(ShiftLeftExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> ">>"
    * identifier1 -> Identifier()
    */
   public void visit(ShiftRightExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> ">>>"
    * identifier1 -> Identifier()
    */
   public void visit(ShiftRightUnsignedExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "+"
    * nodeToken1 -> "["
    * identifierList -> IdentifierList()
    * nodeToken2 -> "]"
    */
   public void visit(PlusOffset n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifierList.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "+"
    * identifier1 -> Identifier()
    */
   public void visit(PlusExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "-"
    * identifier1 -> Identifier()
    */
   public void visit(MinusExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "*"
    * nodeToken1 -> "["
    * identifierList -> IdentifierList()
    * nodeToken2 -> "]"
    */
   public void visit(TimesOffset n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifierList.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "*"
    * identifier1 -> Identifier()
    */
   public void visit(TimesExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "/"
    * nodeToken1 -> "["
    * identifierList -> IdentifierList()
    * nodeToken2 -> "]"
    */
   public void visit(DivideOffset n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifierList.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "/"
    * identifier1 -> Identifier()
    */
   public void visit(DivideExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "%"
    * identifier1 -> Identifier()
    */
   public void visit(ModulusExpression n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * nodeToken -> "["
    * nodeToken1 -> "0 :"
    * identifier -> Identifier()
    * nodeToken2 -> "]"
    */
   public void visit(RegionConstant n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "sin"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(SinExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "cos"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(CosExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "pow"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ","
    * identifier1 -> Identifier()
    * nodeToken5 -> ")"
    */
   public void visit(PowExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
      n.identifier1.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "exp"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(ExpExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "sqrt"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(SqrtExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "abs"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(AbsExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "min"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ","
    * identifier1 -> Identifier()
    * nodeToken5 -> ")"
    */
   public void visit(MinExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
      n.identifier1.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "max"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ","
    * identifier1 -> Identifier()
    * nodeToken5 -> ")"
    */
   public void visit(MaxExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
      n.identifier1.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "log"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(LogExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifier.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * nodeToken -> "~"
    * identifier -> Identifier()
    */
   public void visit(ComplimentExpression n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> "!"
    * identifier -> Identifier()
    */
   public void visit(NotExpression n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "int"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToIntExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "double"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToDoubleExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "long"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToLongExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "short"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToShortExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * nodeToken1 -> "byte"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToByteExpression n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
   }

   /**
    * nodeToken -> "("
    * typeAnnotation -> TypeAnnotation()
    * nodeToken1 -> ")"
    * nodeToken2 -> "("
    * expression -> Expression()
    * nodeToken3 -> ")"
    */
   public void visit(TypeAnnotatedExpression n) {
      n.nodeToken.accept(this);
      n.typeAnnotation.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.expression.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * nodeChoice -> UpdatableArrayType()
    *       | ValueArrayType()
    *       | DistType()
    *       | RegionType()
    *       | PointType()
    */
   public void visit(TypeAnnotation n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "place.places"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    */
   public void visit(Place n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "System.currentTimeMillis"
    * nodeToken1 -> "("
    * nodeToken2 -> ")"
    */
   public void visit(CurrentTime n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * identifier1 -> Identifier()
    * nodeToken1 -> "]"
    */
   public void visit(ArrayAccess n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "[0]"
    */
   public void visit(PointAccess n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( IdentifierList() )?
    * nodeToken2 -> ")"
    */
   public void visit(MethodCall n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
      n.nodeToken1.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "this"
    * nodeToken1 -> "."
    * identifier -> Identifier()
    * nodeToken2 -> "("
    * nodeOptional -> ( IdentifierList() )?
    * nodeToken3 -> ")"
    */
   public void visit(MethodCallInConstructor n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "id"
    */
   public void visit(DotId n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    * nodeToken1 -> "."
    * nodeToken2 -> "get"
    * nodeToken3 -> "("
    * identifierList -> IdentifierList()
    * nodeToken4 -> ")"
    */
   public void visit(DotIdentifierDotGet n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.identifierList.accept(this);
      n.nodeToken4.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "next"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotNext n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "prev"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotPrev n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "isFirst"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotIsFirst n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "isLast"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotIsLast n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "region"
    * nodeToken2 -> "."
    * nodeToken3 -> "size"
    * nodeToken4 -> "("
    * nodeToken5 -> ")"
    */
   public void visit(DotRegionDotSize n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    */
   public void visit(DotIdentifier n) {
      n.identifier.accept(this);
      n.nodeToken.accept(this);
      n.identifier1.accept(this);
   }

   /**
    * nodeToken -> "new"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> [ IdentifierList() ]
    * nodeToken2 -> ")"
    */
   public void visit(NewObject n) {
      n.nodeToken.accept(this);
      n.identifier.accept(this);
      n.nodeToken1.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken2.accept(this);
   }

   /**
    * nodeToken -> "new"
    * nonArrayType -> NonArrayType()
    * nodeToken1 -> "value"
    * nodeToken2 -> "["
    * identifier -> Identifier()
    * nodeToken3 -> "]"
    * arrayInitializer -> ArrayInitializer()
    */
   public void visit(NewValueArray n) {
      n.nodeToken.accept(this);
      n.nonArrayType.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.identifier.accept(this);
      n.nodeToken3.accept(this);
      n.arrayInitializer.accept(this);
   }

   /**
    * nodeToken -> "new"
    * nonArrayType -> NonArrayType()
    * nodeToken1 -> "["
    * identifier -> Identifier()
    * nodeToken2 -> "]"
    * nodeOptional -> [ ArrayInitializer() ]
    */
   public void visit(NewUpdatableArray n) {
      n.nodeToken.accept(this);
      n.nonArrayType.accept(this);
      n.nodeToken1.accept(this);
      n.identifier.accept(this);
      n.nodeToken2.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * nodeToken -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <LONG_LITERAL>
    */
   public void visit(LongLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <HEX_LITERAL>
    */
   public void visit(HexLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <FLOATING_POINT_LITERAL>
    */
   public void visit(FloatingPointLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <STRING_LITERAL>
    */
   public void visit(StringLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "true"
    */
   public void visit(True n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "false"
    */
   public void visit(False n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "here"
    */
   public void visit(HereLiteral n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "place.FIRST_PLACE"
    */
   public void visit(PlaceFirstPlace n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "place.LAST_PLACE"
    */
   public void visit(PlaceLastPlace n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "place.MAX_PLACES"
    */
   public void visit(PlaceMaxPlaces n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "java.lang.Integer.SIZE"
    */
   public void visit(JavaIntegerSize n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "("
    * pointType -> PointType()
    * explodedSpecification -> ExplodedSpecification()
    * nodeToken1 -> ")"
    * block -> Block()
    */
   public void visit(ArrayInitializer n) {
      n.nodeToken.accept(this);
      n.pointType.accept(this);
      n.explodedSpecification.accept(this);
      n.nodeToken1.accept(this);
      n.block.accept(this);
   }

}
