//
// Generated by JTB 1.3.2
//

package uplasmax10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "async"
 * nodeToken1 -> "("
 * identifier -> Identifier()
 * nodeToken2 -> ")"
 * nodeToken3 -> "{"
 * nodeToken4 -> "this"
 * nodeToken5 -> "."
 * identifier1 -> Identifier()
 * nodeToken6 -> "("
 * identifier2 -> Identifier()
 * nodeToken7 -> ")"
 * nodeToken8 -> ";"
 * nodeToken9 -> "}"
 */
public class AsyncStatementInConstructor implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public Identifier identifier;
   public NodeToken nodeToken2;
   public NodeToken nodeToken3;
   public NodeToken nodeToken4;
   public NodeToken nodeToken5;
   public Identifier identifier1;
   public NodeToken nodeToken6;
   public Identifier identifier2;
   public NodeToken nodeToken7;
   public NodeToken nodeToken8;
   public NodeToken nodeToken9;

   public AsyncStatementInConstructor(NodeToken n0, NodeToken n1, Identifier n2, NodeToken n3, NodeToken n4, NodeToken n5, NodeToken n6, Identifier n7, NodeToken n8, Identifier n9, NodeToken n10, NodeToken n11, NodeToken n12) {
      nodeToken = n0;
      nodeToken1 = n1;
      identifier = n2;
      nodeToken2 = n3;
      nodeToken3 = n4;
      nodeToken4 = n5;
      nodeToken5 = n6;
      identifier1 = n7;
      nodeToken6 = n8;
      identifier2 = n9;
      nodeToken7 = n10;
      nodeToken8 = n11;
      nodeToken9 = n12;
   }

   public AsyncStatementInConstructor(Identifier n0, Identifier n1, Identifier n2) {
      nodeToken = new NodeToken("async");
      nodeToken1 = new NodeToken("(");
      identifier = n0;
      nodeToken2 = new NodeToken(")");
      nodeToken3 = new NodeToken("{");
      nodeToken4 = new NodeToken("this");
      nodeToken5 = new NodeToken(".");
      identifier1 = n1;
      nodeToken6 = new NodeToken("(");
      identifier2 = n2;
      nodeToken7 = new NodeToken(")");
      nodeToken8 = new NodeToken(";");
      nodeToken9 = new NodeToken("}");
   }

   public void accept(uplasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(uplasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(uplasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(uplasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

