//
// Generated by JTB 1.3.2
//

package jplasma.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "public"
 * nodeToken1 -> "final"
 * type -> Type()
 * identifier -> Identifier()
 * nodeToken2 -> ";"
 */
public class InitializableConstantDeclaration implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public Type type;
   public Identifier identifier;
   public NodeToken nodeToken2;

   public InitializableConstantDeclaration(NodeToken n0, NodeToken n1, Type n2, Identifier n3, NodeToken n4) {
      nodeToken = n0;
      nodeToken1 = n1;
      type = n2;
      identifier = n3;
      nodeToken2 = n4;
   }

   public InitializableConstantDeclaration(Type n0, Identifier n1) {
      nodeToken = new NodeToken("public");
      nodeToken1 = new NodeToken("final");
      type = n0;
      identifier = n1;
      nodeToken2 = new NodeToken(";");
   }

   public void accept(jplasma.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasma.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasma.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasma.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

