.TH "GMP_GEN_RANDOM" "1" "Dec 1 2008" "gmp_gen_random" ""
.SH "NAME"
gmp_gen_random \- 

.SH "SYNOPSIS"
.B gmp_gen_random
[\fI???\fR]

.SH "DESCRIPTION"
.PP 

.SH "SEE ALSO"
\fBmillerrabin\fP(1) \fBdup\fP(1), \fBdupd\fP(1)

.SH "LEGAL NOTICE"
gmp_gen_random is released under the GPL.

.SH "REPORTING BUGS"
Please send electronic mail to <dup@cs.du.edu>
