//
// Generated by JTB 1.3.2
//

package jplasmax10.syntaxtree;

/**
 * Grammar production:
 * identifier -> Identifier()
 * nodeToken -> "."
 * nodeToken1 -> "isLast"
 * nodeToken2 -> "("
 * nodeToken3 -> ")"
 */
public class DotIsLast implements Node {
   public Identifier identifier;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;
   public NodeToken nodeToken3;

   public DotIsLast(Identifier n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeToken n4) {
      identifier = n0;
      nodeToken = n1;
      nodeToken1 = n2;
      nodeToken2 = n3;
      nodeToken3 = n4;
   }

   public DotIsLast(Identifier n0) {
      identifier = n0;
      nodeToken = new NodeToken(".");
      nodeToken1 = new NodeToken("isLast");
      nodeToken2 = new NodeToken("(");
      nodeToken3 = new NodeToken(")");
   }

   public void accept(jplasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

