//
// Generated by JTB 1.3.2
//

package tplasmax10.syntaxtree;

/**
 * Grammar production:
 * f0 -> "("
 * f1 -> PointType()
 * f2 -> ExplodedSpecification()
 * f3 -> ")"
 * f4 -> Block()
 */
public class ArrayInitializer implements Node {
   public NodeToken f0;
   public PointType f1;
   public ExplodedSpecification f2;
   public NodeToken f3;
   public Block f4;

   public ArrayInitializer(NodeToken n0, PointType n1, ExplodedSpecification n2, NodeToken n3, Block n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public ArrayInitializer(PointType n0, ExplodedSpecification n1, Block n2) {
      f0 = new NodeToken("(");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken(")");
      f4 = n2;
   }

   public void accept(tplasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(tplasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(tplasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(tplasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

