//
// Generated by JTB 1.3.2
//

package jplasmax10.visitor;
import java.util.*;

import jplasmax10.syntaxtree.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * mainClass -> MainClass()
    * programClass -> ProgramClass()
    * nodeListOptional -> ( TopLevelDeclaration() )*
    * nodeToken -> <EOF>
    */
   public void visit(File n);

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "class"
    * identifier -> Identifier()
    * nodeToken2 -> "{"
    * nodeToken3 -> "public"
    * nodeToken4 -> "static"
    * nodeToken5 -> "void"
    * nodeToken6 -> "main"
    * nodeToken7 -> "("
    * nodeToken8 -> "String"
    * nodeToken9 -> "["
    * nodeToken10 -> "]"
    * identifier1 -> Identifier()
    * nodeToken11 -> ")"
    * nodeToken12 -> "{"
    * identifier2 -> Identifier()
    * nodeToken13 -> "."
    * identifier3 -> Identifier()
    * nodeToken14 -> "("
    * nodeToken15 -> ")"
    * nodeToken16 -> ";"
    * nodeToken17 -> "}"
    * nodeToken18 -> "}"
    */
   public void visit(MainClass n);

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( ConstantDeclaration() )*
    * nodeListOptional1 -> ( StaticMethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ProgramClass n);

   /**
    * nodeChoice -> ClassDeclaration()
    *       | ValueDeclaration()
    */
   public void visit(TopLevelDeclaration n);

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( InitializableConstantDeclaration() )*
    * nodeListOptional1 -> ( UpdatableFieldDeclaration() )*
    * nodeListOptional2 -> ( ConstructorDeclaration() )*
    * nodeListOptional3 -> ( MethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ClassDeclaration n);

   /**
    * nodeToken -> "value"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( InitializableConstantDeclaration() )*
    * nodeListOptional1 -> ( ConstructorDeclaration() )*
    * nodeListOptional2 -> ( MethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ValueDeclaration n);

   /**
    * nodeToken -> "public"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(ConstructorDeclaration n);

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "static"
    * nodeToken2 -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken3 -> "="
    * methodCall -> MethodCall()
    * nodeToken4 -> ";"
    */
   public void visit(ConstantDeclaration n);

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken2 -> ";"
    */
   public void visit(InitializableConstantDeclaration n);

   /**
    * nodeToken -> "public"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> ";"
    */
   public void visit(UpdatableFieldDeclaration n);

   /**
    * nodeToken -> "public"
    * nodeToken1 -> "static"
    * returnType -> ReturnType()
    * identifier -> Identifier()
    * nodeToken2 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken3 -> ")"
    * block -> Block()
    */
   public void visit(StaticMethodDeclaration n);

   /**
    * nodeToken -> "public"
    * returnType -> ReturnType()
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(MethodDeclaration n);

   /**
    * finalFormalParameter -> FinalFormalParameter()
    * nodeListOptional -> ( FormalParameterRest() )*
    */
   public void visit(FormalParameterList n);

   /**
    * nodeToken -> "final"
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(FinalFormalParameter n);

   /**
    * nodeToken -> ","
    * finalFormalParameter -> FinalFormalParameter()
    */
   public void visit(FormalParameterRest n);

   /**
    * nodeChoice -> VoidType()
    *       | Type()
    */
   public void visit(ReturnType n);

   /**
    * nodeToken -> "void"
    */
   public void visit(VoidType n);

   /**
    * nodeChoice -> UpdatableArrayType()
    *       | NonArrayType()
    */
   public void visit(Type n);

   /**
    * nonArrayType -> NonArrayType()
    * nodeToken -> "["
    * nodeToken1 -> "]"
    */
   public void visit(UpdatableArrayType n);

   /**
    * nodeChoice -> BooleanType()
    *       | ByteType()
    *       | ShortType()
    *       | IntegerType()
    *       | LongType()
    *       | DoubleType()
    *       | StringType()
    *       | PlaceType()
    *       | ClassNameType()
    */
   public void visit(NonArrayType n);

   /**
    * nodeToken -> "boolean"
    */
   public void visit(BooleanType n);

   /**
    * nodeToken -> "byte"
    */
   public void visit(ByteType n);

   /**
    * nodeToken -> "short"
    */
   public void visit(ShortType n);

   /**
    * nodeToken -> "int"
    */
   public void visit(IntegerType n);

   /**
    * nodeToken -> "long"
    */
   public void visit(LongType n);

   /**
    * nodeToken -> "double"
    */
   public void visit(DoubleType n);

   /**
    * nodeToken -> "String"
    */
   public void visit(StringType n);

   /**
    * nodeToken -> "place"
    */
   public void visit(PlaceType n);

   /**
    * identifier -> Identifier()
    */
   public void visit(ClassNameType n);

   /**
    * nodeToken -> <IDENTIFIER>
    */
   public void visit(Identifier n);

   /**
    * nodeToken -> "{"
    * nodeListOptional -> ( Statement() )*
    * nodeToken1 -> "}"
    */
   public void visit(Block n);

   /**
    * nodeChoice -> Assignment()
    *       | ArrayAssignment()
    *       | FieldAssignment()
    *       | ThisFieldAssignment()
    *       | AsyncStatement()
    *       | Block()
    *       | BreakStatement()
    *       | ContinueStatement()
    *       | DoStatement()
    *       | FinishStatement()
    *       | IfStatement()
    *       | LoopStatement()
    *       | MethodCallStatement()
    *       | MethodCallStatementInConstructor()
    *       | PrintlnStatement()
    *       | PrintStatement()
    *       | PrintErrorStatement()
    *       | ReturnStatement()
    *       | SwitchStatement()
    *       | ThrowStatement()
    *       | WhileStatement()
    *       | FinalVariableDeclaration()
    *       | UpdatableVariableDeclaration()
    */
   public void visit(Statement n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(Assignment n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * identifierList -> IdentifierList()
    * nodeToken1 -> "]"
    * nodeToken2 -> "="
    * identifier1 -> Identifier()
    * nodeToken3 -> ";"
    */
   public void visit(ArrayAssignment n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    * nodeToken1 -> "="
    * nodeToken2 -> "("
    * identifier2 -> Identifier()
    * nodeToken3 -> ")"
    * nodeToken4 -> ";"
    */
   public void visit(FieldAssignment n);

   /**
    * nodeToken -> "this"
    * nodeToken1 -> "."
    * identifier -> Identifier()
    * nodeToken2 -> "="
    * nodeToken3 -> "("
    * identifier1 -> Identifier()
    * nodeToken4 -> ")"
    * nodeToken5 -> ";"
    */
   public void visit(ThisFieldAssignment n);

   /**
    * nodeToken -> "async"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(AsyncStatement n);

   /**
    * nodeToken -> "break"
    * nodeToken1 -> ";"
    */
   public void visit(BreakStatement n);

   /**
    * nodeToken -> "continue"
    * nodeToken1 -> ";"
    */
   public void visit(ContinueStatement n);

   /**
    * nodeToken -> "do"
    * block -> Block()
    * nodeToken1 -> "while"
    * nodeToken2 -> "("
    * identifier -> Identifier()
    * nodeToken3 -> ")"
    * nodeToken4 -> ";"
    */
   public void visit(DoStatement n);

   /**
    * nodeToken -> "finish"
    * block -> Block()
    */
   public void visit(FinishStatement n);

   /**
    * nodeToken -> "if"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * block -> Block()
    * nodeOptional -> [ ElseClause() ]
    */
   public void visit(IfStatement n);

   /**
    * nodeToken -> "else"
    * block -> Block()
    */
   public void visit(ElseClause n);

   /**
    * nodeToken -> "for"
    * nodeToken1 -> "("
    * nodeToken2 -> "int"
    * identifier -> Identifier()
    * nodeToken3 -> "="
    * integerLiteral -> IntegerLiteral()
    * nodeToken4 -> ";"
    * identifier1 -> Identifier()
    * nodeToken5 -> "<"
    * identifier2 -> Identifier()
    * nodeToken6 -> ";"
    * identifier3 -> Identifier()
    * nodeToken7 -> "++"
    * nodeToken8 -> ")"
    * block -> Block()
    */
   public void visit(LoopStatement n);

   /**
    * identifier -> Identifier()
    * nodeListOptional -> ( IdentifierRest() )*
    */
   public void visit(IdentifierList n);

   /**
    * nodeToken -> ","
    * identifier -> Identifier()
    */
   public void visit(IdentifierRest n);

   /**
    * methodCall -> MethodCall()
    * nodeToken -> ";"
    */
   public void visit(MethodCallStatement n);

   /**
    * methodCallInConstructor -> MethodCallInConstructor()
    * nodeToken -> ";"
    */
   public void visit(MethodCallStatementInConstructor n);

   /**
    * nodeToken -> "System.out.println"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintlnStatement n);

   /**
    * nodeToken -> "System.out.print"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintStatement n);

   /**
    * nodeToken -> "System.err.println"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintErrorStatement n);

   /**
    * nodeToken -> "return"
    * nodeOptional -> [ Identifier() ]
    * nodeToken1 -> ";"
    */
   public void visit(ReturnStatement n);

   /**
    * nodeToken -> "switch"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * nodeListOptional -> ( SwitchEntry() )*
    * nodeToken4 -> "}"
    */
   public void visit(SwitchStatement n);

   /**
    * switchLabel -> SwitchLabel()
    * nodeToken -> ":"
    * block -> Block()
    */
   public void visit(SwitchEntry n);

   /**
    * nodeChoice -> Case()
    *       | Default()
    */
   public void visit(SwitchLabel n);

   /**
    * nodeToken -> "case"
    * identifier -> Identifier()
    */
   public void visit(Case n);

   /**
    * nodeToken -> "default"
    */
   public void visit(Default n);

   /**
    * nodeToken -> "throw"
    * nodeToken1 -> "new"
    * nodeToken2 -> "RuntimeException"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    * nodeToken5 -> ";"
    */
   public void visit(ThrowStatement n);

   /**
    * nodeToken -> "while"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    * block -> Block()
    */
   public void visit(WhileStatement n);

   /**
    * nodeToken -> "final"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> "="
    * expression -> Expression()
    * nodeToken2 -> ";"
    */
   public void visit(FinalVariableDeclaration n);

   /**
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(UpdatableVariableDeclaration n);

   /**
    * nodeChoice -> ExpressionInParentheses()
    *       | ConditionalOrExpression()
    *       | ConditionalAndExpression()
    *       | InclusiveOrExpression()
    *       | ExclusiveOrExpression()
    *       | AndExpression()
    *       | EqualsExpression()
    *       | NonEqualsExpression()
    *       | LessThanExpression()
    *       | GreaterThanExpression()
    *       | LessThanEqualExpression()
    *       | GreaterThanEqualExpression()
    *       | ShiftLeftExpression()
    *       | ShiftRightExpression()
    *       | ShiftRightUnsignedExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivideExpression()
    *       | ModulusExpression()
    *       | SinExpression()
    *       | CosExpression()
    *       | PowExpression()
    *       | ExpExpression()
    *       | SqrtExpression()
    *       | AbsExpression()
    *       | MinExpression()
    *       | MaxExpression()
    *       | LogExpression()
    *       | ComplimentExpression()
    *       | NotExpression()
    *       | CoercionToIntExpression()
    *       | CoercionToDoubleExpression()
    *       | CoercionToLongExpression()
    *       | CoercionToShortExpression()
    *       | CoercionToByteExpression()
    *       | Place()
    *       | CurrentTime()
    *       | ArrayAccess()
    *       | MethodCall()
    *       | MethodCallInConstructor()
    *       | DotId()
    *       | DotIdentifierDotGet()
    *       | DotNext()
    *       | DotPrev()
    *       | DotIsFirst()
    *       | DotIsLast()
    *       | DotLength()
    *       | DotIdentifier()
    *       | NewObject()
    *       | NewUpdatableArray()
    *       | IntegerLiteral()
    *       | LongLiteral()
    *       | HexLiteral()
    *       | FloatingPointLiteral()
    *       | StringLiteral()
    *       | True()
    *       | False()
    *       | HereLiteral()
    *       | PlaceFirstPlace()
    *       | PlaceLastPlace()
    *       | PlaceMaxPlaces()
    *       | JavaIntegerSize()
    *       | Identifier()
    */
   public void visit(Expression n);

   /**
    * nodeToken -> "("
    * expression -> Expression()
    * nodeToken1 -> ")"
    */
   public void visit(ExpressionInParentheses n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "||"
    * identifier1 -> Identifier()
    */
   public void visit(ConditionalOrExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "&&"
    * identifier1 -> Identifier()
    */
   public void visit(ConditionalAndExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "|"
    * identifier1 -> Identifier()
    */
   public void visit(InclusiveOrExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "^"
    * identifier1 -> Identifier()
    */
   public void visit(ExclusiveOrExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "&"
    * identifier1 -> Identifier()
    */
   public void visit(AndExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "=="
    * identifier1 -> Identifier()
    */
   public void visit(EqualsExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "!="
    * identifier1 -> Identifier()
    */
   public void visit(NonEqualsExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "<"
    * identifier1 -> Identifier()
    */
   public void visit(LessThanExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> ">"
    * identifier1 -> Identifier()
    */
   public void visit(GreaterThanExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "<="
    * identifier1 -> Identifier()
    */
   public void visit(LessThanEqualExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> ">="
    * identifier1 -> Identifier()
    */
   public void visit(GreaterThanEqualExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "<<"
    * identifier1 -> Identifier()
    */
   public void visit(ShiftLeftExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> ">>"
    * identifier1 -> Identifier()
    */
   public void visit(ShiftRightExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> ">>>"
    * identifier1 -> Identifier()
    */
   public void visit(ShiftRightUnsignedExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "+"
    * identifier1 -> Identifier()
    */
   public void visit(PlusExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "-"
    * identifier1 -> Identifier()
    */
   public void visit(MinusExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "*"
    * identifier1 -> Identifier()
    */
   public void visit(TimesExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "/"
    * identifier1 -> Identifier()
    */
   public void visit(DivideExpression n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "%"
    * identifier1 -> Identifier()
    */
   public void visit(ModulusExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "sin"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(SinExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "cos"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(CosExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "pow"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ","
    * identifier1 -> Identifier()
    * nodeToken5 -> ")"
    */
   public void visit(PowExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "exp"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(ExpExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "sqrt"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(SqrtExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "abs"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(AbsExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "min"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ","
    * identifier1 -> Identifier()
    * nodeToken5 -> ")"
    */
   public void visit(MinExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "max"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ","
    * identifier1 -> Identifier()
    * nodeToken5 -> ")"
    */
   public void visit(MaxExpression n);

   /**
    * nodeToken -> "Math"
    * nodeToken1 -> "."
    * nodeToken2 -> "log"
    * nodeToken3 -> "("
    * identifier -> Identifier()
    * nodeToken4 -> ")"
    */
   public void visit(LogExpression n);

   /**
    * nodeToken -> "~"
    * identifier -> Identifier()
    */
   public void visit(ComplimentExpression n);

   /**
    * nodeToken -> "!"
    * identifier -> Identifier()
    */
   public void visit(NotExpression n);

   /**
    * nodeToken -> "("
    * nodeToken1 -> "int"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToIntExpression n);

   /**
    * nodeToken -> "("
    * nodeToken1 -> "double"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToDoubleExpression n);

   /**
    * nodeToken -> "("
    * nodeToken1 -> "long"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToLongExpression n);

   /**
    * nodeToken -> "("
    * nodeToken1 -> "short"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToShortExpression n);

   /**
    * nodeToken -> "("
    * nodeToken1 -> "byte"
    * nodeToken2 -> ")"
    * expression -> Expression()
    */
   public void visit(CoercionToByteExpression n);

   /**
    * nodeToken -> "place.places"
    * nodeToken1 -> "("
    * identifier -> Identifier()
    * nodeToken2 -> ")"
    */
   public void visit(Place n);

   /**
    * nodeToken -> "System.currentTimeMillis"
    * nodeToken1 -> "("
    * nodeToken2 -> ")"
    */
   public void visit(CurrentTime n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * identifier1 -> Identifier()
    * nodeToken1 -> "]"
    */
   public void visit(ArrayAccess n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( IdentifierList() )?
    * nodeToken2 -> ")"
    */
   public void visit(MethodCall n);

   /**
    * nodeToken -> "this"
    * nodeToken1 -> "."
    * identifier -> Identifier()
    * nodeToken2 -> "("
    * nodeOptional -> ( IdentifierList() )?
    * nodeToken3 -> ")"
    */
   public void visit(MethodCallInConstructor n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "id"
    */
   public void visit(DotId n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    * nodeToken1 -> "."
    * nodeToken2 -> "get"
    * nodeToken3 -> "("
    * identifierList -> IdentifierList()
    * nodeToken4 -> ")"
    */
   public void visit(DotIdentifierDotGet n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "next"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotNext n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "prev"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotPrev n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "isFirst"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotIsFirst n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "isLast"
    * nodeToken2 -> "("
    * nodeToken3 -> ")"
    */
   public void visit(DotIsLast n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * nodeToken1 -> "length"
    */
   public void visit(DotLength n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "."
    * identifier1 -> Identifier()
    */
   public void visit(DotIdentifier n);

   /**
    * nodeToken -> "new"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> [ IdentifierList() ]
    * nodeToken2 -> ")"
    */
   public void visit(NewObject n);

   /**
    * nodeToken -> "new"
    * nonArrayType -> NonArrayType()
    * nodeToken1 -> "["
    * identifier -> Identifier()
    * nodeToken2 -> "]"
    */
   public void visit(NewUpdatableArray n);

   /**
    * nodeToken -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n);

   /**
    * nodeToken -> <LONG_LITERAL>
    */
   public void visit(LongLiteral n);

   /**
    * nodeToken -> <HEX_LITERAL>
    */
   public void visit(HexLiteral n);

   /**
    * nodeToken -> <FLOATING_POINT_LITERAL>
    */
   public void visit(FloatingPointLiteral n);

   /**
    * nodeToken -> <STRING_LITERAL>
    */
   public void visit(StringLiteral n);

   /**
    * nodeToken -> "true"
    */
   public void visit(True n);

   /**
    * nodeToken -> "false"
    */
   public void visit(False n);

   /**
    * nodeToken -> "here"
    */
   public void visit(HereLiteral n);

   /**
    * nodeToken -> "place.FIRST_PLACE"
    */
   public void visit(PlaceFirstPlace n);

   /**
    * nodeToken -> "place.LAST_PLACE"
    */
   public void visit(PlaceLastPlace n);

   /**
    * nodeToken -> "place.MAX_PLACES"
    */
   public void visit(PlaceMaxPlaces n);

   /**
    * nodeToken -> "java.lang.Integer.SIZE"
    */
   public void visit(JavaIntegerSize n);

}

