//
// Generated by JTB 1.3.2
//

package jplasmax10.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "do"
 * block -> Block()
 * nodeToken1 -> "while"
 * nodeToken2 -> "("
 * identifier -> Identifier()
 * nodeToken3 -> ")"
 * nodeToken4 -> ";"
 */
public class DoStatement implements Node {
   public NodeToken nodeToken;
   public Block block;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;
   public Identifier identifier;
   public NodeToken nodeToken3;
   public NodeToken nodeToken4;

   public DoStatement(NodeToken n0, Block n1, NodeToken n2, NodeToken n3, Identifier n4, NodeToken n5, NodeToken n6) {
      nodeToken = n0;
      block = n1;
      nodeToken1 = n2;
      nodeToken2 = n3;
      identifier = n4;
      nodeToken3 = n5;
      nodeToken4 = n6;
   }

   public DoStatement(Block n0, Identifier n1) {
      nodeToken = new NodeToken("do");
      block = n0;
      nodeToken1 = new NodeToken("while");
      nodeToken2 = new NodeToken("(");
      identifier = n1;
      nodeToken3 = new NodeToken(")");
      nodeToken4 = new NodeToken(";");
   }

   public void accept(jplasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jplasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jplasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jplasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

