//
// Generated by JTB 1.3.2
//

package uplasmax10.syntaxtree;

/**
 * Grammar production:
 * methodCallInConstructor -> MethodCallInConstructor()
 * nodeToken -> ";"
 */
public class MethodCallStatementInConstructor implements Node {
   public MethodCallInConstructor methodCallInConstructor;
   public NodeToken nodeToken;

   public MethodCallStatementInConstructor(MethodCallInConstructor n0, NodeToken n1) {
      methodCallInConstructor = n0;
      nodeToken = n1;
   }

   public MethodCallStatementInConstructor(MethodCallInConstructor n0) {
      methodCallInConstructor = n0;
      nodeToken = new NodeToken(";");
   }

   public void accept(uplasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(uplasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(uplasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(uplasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

