//
// Generated by JTB 1.3.2
//

package uplasmax10.syntaxtree;

/**
 * Grammar production:
 * identifier -> Identifier()
 * nodeToken -> "[0]"
 */
public class PointAccess implements Node {
   public Identifier identifier;
   public NodeToken nodeToken;

   public PointAccess(Identifier n0, NodeToken n1) {
      identifier = n0;
      nodeToken = n1;
   }

   public PointAccess(Identifier n0) {
      identifier = n0;
      nodeToken = new NodeToken("[0]");
   }

   public void accept(uplasmax10.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(uplasmax10.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(uplasmax10.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(uplasmax10.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

